/* do not change this file, it is auto generated by storybook. */

import {
  configure,
  addDecorator,
  addParameters,
} from "@storybook/react-native";

import { loadStories } from "./storyLoader";

import { decorators, parameters } from "./preview";

if (decorators) {
  decorators.forEach(decorator => addDecorator(decorator));
}

if (parameters) {
  addParameters(parameters);
}

configure(loadStories, module);
